Updated docs for new crypto builtins
Zilliqa/scilla-docs pull request #144
Opened 2021-07-01 01:23 UTC by AHaliq

2021-07-01 07:37 UTC, anton-trunov commented on docs/source/scilla-in-depth.rst
> +  the sum of the points in the underlying group G1. The input points and the result option of a point are each a ``Some (Pair Bystr32 ByStr32)``.
Let's tweak this description a bit to match the style of the other option-valued builtins. For instance, just above this paragraph it says:

> The return type is ``Option String``. On success, ``Some addr`` is returned and on invalid inputs ``None`` is returned.

2021-07-01 07:39 UTC, anton-trunov commented on docs/source/scilla-in-depth.rst
> +  and uses the generator of the curve to performs multiplication. The result is an option of a point on the curve.
```suggestion
- ``builtin alt_bn128_G1_bmul s``. It is known as basepoint multiplication; the builtin takes a scalar ``ByStr32`` value ``s``
  and uses the generator of the curve to perform multiplication. The result is an option of a point on the curve.
```

2021-07-01 16:30 UTC, anton-trunov requested changes

2021-07-01 16:30 UTC, anton-trunov commented on docs/source/scilla-in-depth.rst
> +  the sum of the points in the underlying group G1. The input points and the result option of a point are each a ``Some (Pair (Bystr32) (ByStr32))``.
Let's make this sentence look like the rest of them.

2021-07-01 16:30 UTC, anton-trunov commented on docs/source/scilla-in-depth.rst
> +  and a scalar ``ByStr32`` value ``s`` and returns the sum of the point ``p`` taken ``s`` times. The result is ``Option (Pair (ByStr32) (ByStr32))``.
We should say something about the cases when the result is `Some ...` and `None`.

2021-07-01 16:30 UTC, anton-trunov commented on docs/source/scilla-in-depth.rst
> +- ``builtin alt_bn128_G1_neg p``. The builtin takes a point ``p`` on the ``alt_bn128`` curve and returns the negation of the point/
Same here. Is `/` supposed to be `.`?

2021-07-01 16:55 UTC, anton-trunov approved these changes

2021-07-05 08:21 UTC, jjcnn commented
Are the changes documented here part of the Scilla update we've just released? If they are, then we should merge this PR, but if they aren't then it might be better to wait until the next release.

2021-07-05 10:14 UTC, anton-trunov approved these changes

2021-07-05 10:16 UTC, anton-trunov commented
@jjcnn These builtins are not part of the most recent Scilla release. Let's wait then. (We should really have versioning for docs as we have been discussing for a number of months)

2022-01-27 07:23 UTC, jjcnn commented
@anton-trunov : What's the status on these crypto buildins? Are they part of Scilla now, or did we abandon them?

2022-01-27 09:10 UTC, anton-trunov commented
Yes, the linked PRs have been merged.

2022-01-27 09:10 UTC, merged